unbind = Super, G
$kbGames = Super, G
bind = $kbGames, exec, caelestia toggle games

monitor = HDMI-A-1, 3840x2160@119, 0x0, 1, bitdepth, 10,
monitor = DP-1, 2560x1440@144, 3840x0, 1, bitdepth, 10, transform, 3

misc {
    vrr = 0
}

